# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      - name: Azure Login
        uses: Azure/login@v1.1
        with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         enable-AzPSSession: false

      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v1
        with:
          packer-version: 1.7.5
     
      - name: Packer Validate
      # You may pin to the exact commit or the version.
        uses: hashicorp/packer-github-actions@v0.2.0
        with:
          # command to execute
          command: validate
          # arguments for command
          # file(s) to target
          target: ubuntu2004.json

      - name: Packer build
      # You may pin to the exact commit or the version.
        uses: hashicorp/packer-github-actions@v0.2.0
        with:
          # command to execute
          command: build
          # arguments for command
          # file(s) to target
          target: ubuntu2004.json
          
      - name: Azure CLI Logout
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az logout
            az cache purge
            az account clear    
          
        
          
