# This is a basic workflow to help you get started with Actions

name: packer-image-backery

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      - name: Azure Login
        uses: Azure/login@v1.1
        with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         enable-AzPSSession: true
         
      - name: install latest packer binary
        uses: hashicorp-contrib/setup-packer@v1

      - name: packer validate
        run: packer validate ubuntu2004.json
        env: # Or as an environment variable
         SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

      - name: packer build 
        run: packer build ubuntu2004.json
        env: # Or as an environment variable
         SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
